### ISSUE TITLE
Meteor must run in fiber on running n4jdb query on server side

### ISSUE THREAD

**Issue by Neobii** [VeliovGroup/ostrio-neo4jdriver#11]
I have this code:
```javascript
Contacts = Meteor.neo4j.collection('contacts');
---
Meteor.methods({
	insertNeoUser: function(){
		Meteor.N4JDB.query('CREATE (a:Contact {name: "test"})');
	}
})
```

Whenever I call that method, I get this error:

Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20150506-16:08:33.044(-4)? (STDERR)   at Object.Meteor._nodeCodeMustBeInFiber (/home/user/Desktop/newreact/reaction/.meteor/local/build/programs/server/packages/meteor.js:942:11)

**Comment by Neobii** [comment]
full stack trace: https://gist.github.com/Neobii/6669dbf5432b53013fa4

**Comment by Neobii** [comment]
This issue is from using `Meteor.methods` instead of  `Meteor.neo4j.methods`.  Is there any reason why you don't want to use Meteor.methods or Meteor.call besides possibly the fiber stuff?  This makes it hard to integrate into a lot of pre-existing packages like simple schema etc.

**Comment by dr-dimitru** [comment]
Hi @Neobii ,
Again sorry for late response.
Do you using Neo4jReactivity or Neo4jDriver?

**Comment by dr-dimitru** [comment]
@Neobii inside `Meteor.neo4j.methods` we do some [magic](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/ostrio:neo4jreactivity_driver.coffee#L668) to let them be reactive

**Comment by dr-dimitru** [comment]
@Neobii any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence on contributor end.
And we are can not implement this issue
