### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by blackslate** [VeliovGroup/ostrio-neo4jdriver#22]
Please check out my "stackOverflow" branch [here](https://github.com/blackslate/ostrio-neo4jDemo/tree/stackOverflow)

In a very simple application, on the server, I create a two nodes in the Neo4j database, and retrieve a cursor for them. In the client, I make a call to a server method; this uses cursor.fetch() and should return the result.

Instead, a "RangeError: Maximum call stack size exceeded" error is output in the Terminal window, and the application is restarted.

**Comment by dr-dimitru** [comment]
@blackslate could you please post stacktrace of this error (should be outputted right before app going to restart)

**Comment by blackslate** [comment]
Here it is. Does the fact that you are asking me for this mean that you have been unable to reproduce the symptom using the repo I provided?

I20150913-19:00:49.943(-4)? v2.2.5            
I20150913-19:00:49.945(-4)? Successfully connected to Neo4j on http://localhost:7474
=> Meteor server restarted
W20150913-19:00:50.198(-4)? (STDERR) 
W20150913-19:00:50.199(-4)? (STDERR) /Users/james/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150913-19:00:50.199(-4)? (STDERR) 						throw(ex);
W20150913-19:00:50.199(-4)? (STDERR) 						      ^
W20150913-19:00:50.200(-4)? (STDERR) RangeError: Maximum call stack size exceeded
=> Exited with code: 8

**Comment by blackslate** [comment]
A node contains a _service property. This appears to contain circular references that cannot be stringified, so the node itself cannot be sent across the wire. Here's a partial representation of a "Hello World" node:

{ _service: 
 { paged_traverse: [Object],
   outgoing_relationships: [Object],
   outgoing_typed_relationships: [Object],
   create_relationship: [Object],
   labels: [Object],
   traverse: [Object],
   all_relationships: [Object],
   all_typed_relationships: [Object],
   property: [Object],
   self: [Object],
   incoming_relationships: [Object],
   properties: [Object],
   incoming_typed_relationships: [Object] },
name: 'Hello World',
id: 36,
labels: [],
metadata: { id: 36, labels: [] } }

**Comment by blackslate** [comment]
The circular reference is due to the `_db` property of the sub-objects of the `_service` object. Each `_db` object refers back to `_service`. I've created a demo where all `_db` objects are removed before the result of  `db.query().fetch()` is shared with the client.

[https://github.com/blackslate/ostrio-neo4jDemo/tree/dbFilter](https://github.com/blackslate/ostrio-neo4jDemo/tree/dbFilter)

This gives the client access to all the data retrieved from the database, except a reference to the `_db` object itself. Since the `_db` object is meaningless on the client, this is a reasonable thing to do.

Question: would it make sense to add a method to ostrio:neo4jdriver which will automatically strip out these `_db` references, so that developers don't have to include a custom chunk of JavaScript of their own that does this?

**Comment by dr-dimitru** [comment]
Should be fixed in https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/a977bf3766db775b4e3a12f2143591c08d31ed5e
Could you please check on your end? (btw all tests is passed)

**Comment by dr-dimitru** [comment]
> Question: would it make sense to add a method to ostrio:neo4jdriver which will automatically strip out these _db references, so that developers don't have to include a custom chunk of JavaScript of their own that does this?

Developers don't need to worry about private properties, if any of them causing errors or any kind of troubles - it is my bad

**Comment by blackslate** [comment]
> On Sep 14, 2015, at 1:16 PM, dr.dimitru <notifications@github.com> wrote:
> 
> Should be fixed in a977bf3 <https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/a977bf3766db775b4e3a12f2143591c08d31ed5e>
> Could you please check on your end? (btw all tests is passed)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/VeliovGroup/ostrio-neo4jdriver/issues/22#issuecomment-140148639>.
> 


Привет, Дмитрий!

Thanks for your fix. My test app now no longer crashes.

db.query("MATCH (node) RETURN node").fetch() now returns an array like this:

[ { node: 
    { _service: undefined,
      name: 'Hello',
      id: 36,
      labels: [],
      metadata: [Object] } },
  { node: 
    { _service: undefined,
      name: 'World',
      id: 37,
      labels: [],
      metadata: [Object]
    }
  }
]

Would it be cleaner to remove the _service key altogether?

Спасибо,

James

**Comment by dr-dimitru** [comment]
Whoops, my bad, fixed in: https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/7698b86b4f691cb192a17f110e22e80994fb142c

**Comment by blackslate** [comment]
> On Sep 14, 2015, at 2:12 PM, dr.dimitru <notifications@github.com> wrote:
> 
> Whoops, my bad, fixed in: 7698b86 <https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/7698b86b4f691cb192a17f110e22e80994fb142c>
> —
> Reply to this email directly or view it on GitHub <https://github.com/VeliovGroup/ostrio-neo4jdriver/issues/22#issuecomment-140163651>.
> 
Nice!

**Comment by blackslate** [comment]
Здравствуйте, Дмитрий!

Вот полный текст из терминала, пожалуйста:

$ git clone https://github.com/VeliovGroup/ostrio-neo4jdriver.git
Cloning into 'ostrio-neo4jdriver'...
remote: Counting objects: 504, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 504 (delta 8), reused 0 (delta 0), pack-reused 474
Receiving objects: 100% (504/504), 126.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (276/276), done.
Checking connectivity... done.
$ cd ostrio-neo4jdriver
$ git checkout dev
Branch dev set up to track remote branch dev from origin.
Switched to a new branch 'dev'

$ git log --oneline
b8bb368 docs
f2671df Add link to demo
1d612fc Overall improvements
bd1e0b7 minor fix
0abde8d Basic app to work with nodes and relationships
7698b86 fix
a977bf3 fix issue #22
:
$ cd demo/
$ meteor
[[[[[ /Volumes/Yata/repos/Meteor/ostrio-neo4jdriver/demo ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: ostrio:neo4jdriver 0.2.15,
   was 1.0.0.
   Constraints on package "ostrio:neo4jdriver":
   
   To allow potentially incompatible changes to top-level dependencies, you must pass
   --allow-incompatible-update on the command line.
   
=> Your application has errors. Waiting for file change.

James

**Comment by dr-dimitru** [comment]
As it still in dev, and driver not published to Atmosphere - you need to install and use driver locally (as we did it before, via symlink and etc.)

**Comment by dr-dimitru** [comment]
See [local usage](https://github.com/VeliovGroup/ostrio-neo4jdriver/tree/dev#local-usage)

**Comment by blackslate** [comment]
jade index.jade -P

/usr/local/lib/node_modules/jade/lib/runtime.js:240
  throw err;
        ^
SyntaxError: index.jade:44
    42|                     .btn-group-vertical(style="width:100%")
    43|                       button.btn.btn-block.btn-primary(type="submit") Update Node
  > 44|                       unless getNodeDegree nodeFrom
    45|                         button.btn.btn-block.btn-danger#deleteNode(type="button") Delete Node
    46|                       else
    47|                         button.btn.btn-block.btn-danger.disabled(type="button" disabled="disabled") Delete Node

**Comment by blackslate** [comment]
Здравствуий, Дмитрий!

Is Alchemy.js still being developed? The "contact us" email address is no longer exists, and the contact us form <http://www.graphalchemist.com/work/> seems to be broken. For all the people shown on the Team page...

Huston Hedinger <https://www.linkedin.com/in/hustonhedinger>
Grace Andrews <https://www.linkedin.com/in/graceandrews>
Isabella Jorissen <https://www.linkedin.com/profile/view?id=ADEAAAxZy-ABmSvBJFuvdb0yQHHSvvhL9QBefXg&authType=NAME_SEARCH&authToken=Vp4G&locale=en_US&srchid=38153801442326702459&srchindex=2&srchtotal=2&trk=vsrp_people_res_name&trkInfo=VSRPsearchId:38153801442326702459,VSRPtargetId:207211488,VSRPcmpt:primary,VSRPnm:true,authType:NAME_SEARCH>
Harland Hauger <https://www.linkedin.com/in/harlandhauger>
Matthew Cox <https://www.linkedin.com/in/mdcoxpdx>
Lori Zanotta <https://www.linkedin.com/in/lorizanotta>

... their LinkedIn profiles mention Graph Alchemist as a "previous" employment, or it's not mentioned at all.

Would it be a good plan to look for an alternative?

James


PS. Is there a better email address that I can use to contact you?

**Comment by dr-dimitru** [comment]
> jade index.jade -P
> /usr/local/lib/node_modules/jade/lib/runtime.js:240

I use jade sugar, so it must be compiled only from meteor package (mquandalle:jade)

**Comment by dr-dimitru** [comment]
In demo I used graph visualization by [visjs](http://visjs.org/), as it mentioned in [docs](https://github.com/VeliovGroup/ostrio-neo4jdriver/tree/dev/demo)

**Comment by blackslate** [comment]
On Sep 15, 2015, at 11:34 AM, dr.dimitru <notifications@github.com> wrote:

> In demo I used graph visualization by visjs <http://visjs.org/>, as it mentioned in docs <https://github.com/VeliovGroup/ostrio-neo4jdriver/tree/dev/demo>
How do you create the Meteor package for visjs?

**Comment by dr-dimitru** [comment]
@blackslate idnk, I mean check the sources. BTW I don't see any troubles here, are you?

**Comment by blackslate** [comment]
On Sep 15, 2015, at 12:34 PM, dr.dimitru <notifications@github.com> wrote:
> @blackslate <https://github.com/blackslate> idnk, I mean check the sources. BTW I don't see any troubles here, are you?
> 
Sure, your demo is working for me. No troubles with it.

In the tutorial, I want to explain how to create the demo from scratch, so that others can do it themselves and adapt it for their own needs.

If you didn't create your own package, which one did you use?

**Comment by dr-dimitru** [comment]
@blackslate Simple as these [3 lines of code][https://github.com/VeliovGroup/ostrio-neo4jdriver/blob/dev/demo/client/index.jade#L1-L3]
