### ISSUE TITLE
App crashes if Neo4j is not running (commit 0a4d290 Update in accordance to new API)

### ISSUE THREAD

**Issue by blackslate** [VeliovGroup/ostrio-neo4jdriver#23]
## Steps to reproduce

Stop Neo4j if it is running.
Launch your Meteor app that uses ostrio:neo4jdriver to connect to the database

## Result
Here's the stack trace

I20150920-19:07:43.507(-4)? Error sending request to Neo4j (GrapheneDB) server:
I20150920-19:07:43.508(-4)? {}
W20150920-19:07:43.508(-4)? (STDERR) 
W20150920-19:07:43.508(-4)? (STDERR) /Users/james/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150920-19:07:43.508(-4)? (STDERR) 						throw(ex);
W20150920-19:07:43.509(-4)? (STDERR) 						      ^
W20150920-19:07:43.610(-4)? (STDERR) Error: Error with connection to Neo4j
W20150920-19:07:43.610(-4)? (STDERR)     at Neo4jDB.__connect (packages/ostrio:neo4jdriver/neo4jdriver.coffee:148:17)
W20150920-19:07:43.610(-4)? (STDERR)     at new Neo4jDB (packages/ostrio:neo4jdriver/neo4jdriver.coffee:54:6)
W20150920-19:07:43.611(-4)? (STDERR)     at app/server/server.js:4:12
W20150920-19:07:43.611(-4)? (STDERR)     at /Volumes/Yata/repos/Meteor/Neo4j/Ostrio/demo/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

## Expected
Elegant failure, with no crash.

**Comment by dr-dimitru** [comment]
Fixed in https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/295fa99ceb8022edc1dd88f7598d3c0aec8bd964
Thank you for contribution.
