### ISSUE TITLE
db.query() fails to throw an error when an invalid query is used

### ISSUE THREAD

**Issue by blackslate** [VeliovGroup/ostrio-neo4jdriver#24]
## Steps to reproduce
- Clone the following repository and use Meteor to run it: https://github.com/blackslate/neo4jdriver-queryError.git
- Check the output in your Terminal window

## Result
An invalid query silently prints out the error to the Terminal, but does not inform the application that the query was not executed.

## Expected
If no callback is provided for a call to the Neo4j database and an error occurs, this error should be throw so that the server-side script can catch it and treat it.

**Comment by dr-dimitru** [comment]
I've used exception-less code for dev stage. But it's good point to discuss - should I leave it like this, or throw exceptions for sync functions.

**Comment by dr-dimitru** [comment]
Fixed in https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/295fa99ceb8022edc1dd88f7598d3c0aec8bd964
Thank you for contribution.
