### ISSUE TITLE
[SOLVED] Error: Cannot find module 'fibers' in Mac Os x and Linux, but not in Windows

### ISSUE THREAD

**Issue by vrfox** [VeliovGroup/ostrio-neo4jdriver#32]
W20160115-12:14:32.077(-7)? (STDERR)          
W20160115-12:14:32.077(-7)? (STDERR) /home/gt/.meteor/packages/meteor-tool/.1.1.10.7k0drq++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160115-12:14:32.078(-7)? (STDERR)                         throw(ex);
W20160115-12:14:32.078(-7)? (STDERR)                               ^
W20160115-12:14:32.082(-7)? (STDERR) Error: Cannot find module 'fibers'
W20160115-12:14:32.082(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160115-12:14:32.083(-7)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160115-12:14:32.084(-7)? (STDERR)     at Module.require (module.js:364:17)
W20160115-12:14:32.085(-7)? (STDERR)     at require (module.js:380:17)
W20160115-12:14:32.085(-7)? (STDERR)     at Object.<anonymous> (/home/gt/.meteor/packages/ostrio_neo4jdriver/.1.0.2.1di8z3p++os+web.browser+web.cordova/npm/node_modules/neo4j-fiber/lib/helpers.js:33:11)
W20160115-12:14:32.085(-7)? (STDERR)     at Object.<anonymous> (/home/gt/.meteor/packages/ostrio_neo4jdriver/.1.0.2.1di8z3p++os+web.browser+web.cordova/npm/node_modules/neo4j-fiber/lib/helpers.js:62:4)
W20160115-12:14:32.085(-7)? (STDERR)     at Module._compile (module.js:456:26)
W20160115-12:14:32.086(-7)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160115-12:14:32.086(-7)? (STDERR)     at Module.load (module.js:356:32)
W20160115-12:14:32.086(-7)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160115-12:14:32.086(-7)? (STDERR)     at Module.require (module.js:364:17)
W20160115-12:14:32.087(-7)? (STDERR)     at require (module.js:380:17)

We are making a project using neo4j, in my windows machine everythings works ok, but in a linux mint and mac os x gets this error.

I dont know why, have searched a lot and found nothing

**Comment by dr-dimitru** [comment]
Hi @vrfox , have you read this one: https://github.com/VeliovGroup/ostrio-neo4jdriver/issues/26 ?

**Comment by vrfox** [comment]
we are 3 persons, and the 3 have read it, still no luck.
The project was started in my machine (windows 10), then by git clone to the others

**Comment by dr-dimitru** [comment]
Fibers not supported on Win (as long as I remember)
Anyways, first - have tried "Fibered" and "Fiberless" versions?

Second try to:
```shell
npm update
npm rebuild
```

If this won't help you, try to use [NPM package](https://github.com/VeliovGroup/neo4j-fiber) directly via `NPM.require('neo4j-fiber');`

**Comment by vrfox** [comment]
the linux machine, is a linux mint mate (backup if something), clean install and just updated, it has only meteor, neo4j, git and brackets to work. I just installed nodejs 5 stable. did the npm update and npm rebuild still nothing

**Comment by dr-dimitru** [comment]
Have you tried "Fibered" and "Fiberless" versions?

**Comment by vrfox** [comment]
Yes i have tried both version in both, mac and linux

**Comment by dr-dimitru** [comment]
And NPM package (from NPM not from atmosphere)

**Comment by vrfox** [comment]
Thats the files packages and versions in .meteor folder

[packages and versions.txt](https://github.com/VeliovGroup/ostrio-neo4jdriver/files/92470/packages.and.versions.txt)

**Comment by dr-dimitru** [comment]
This is atmosphere packages.
Anyways put `ostrio:neo4jdriver` to the very bottom of this file

**Comment by vrfox** [comment]
Sorry, i dont understand that one

**Comment by dr-dimitru** [comment]
Put line with `ostrio:neo4jdriver` to the very bottom of the packages file. Make it last loaded package (order is matters in Meteor).

Also I've read #26 again, and just realised what this is common error for "ported" projects directly from one machine to another. - (if suggestion above won't work) You need to create new project and copy-paste only project's files and dirs (without .meteor and etc.) then just add all packages you need to `.meteor/packages` file.

It is somehow caused by `.id` which generated right after compiling internal Meteor files, like Fibers and etc. packages, written on C

**Comment by vrfox** [comment]
OK.... noob error,
We were changing the -fiber in **package** and no in **versions.**

So in the end was used the 'ostrio:neo4jdriver' and in **versions** file goes the 'ostrio:neo4jdriver@1.0.2-fiber'

In windows using just ostrio:neo4jdriver works without problems

Thank you for all your time

**Comment by dr-dimitru** [comment]
:+1: 
do not forget to star this package :)
