### ISSUE TITLE
Relationships error in MATCH

### ISSUE THREAD

**Issue by vrfox** [VeliovGroup/ostrio-neo4jdriver#33]
With this query

db.query("MATCH p = (n:User {username: 'admin'})-[r*1..3]->(others) RETURN p")

i get this:

=> Exited with code: 8
W20160116-14:36:52.052(-7)? (STDERR) z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\helpers.js:45
W20160116-14:36:52.052(-7)? (STDERR)       }).run();
W20160116-14:36:52.052(-7)? (STDERR)          ^
W20160116-14:36:52.052(-7)? (STDERR) TypeError: Cannot read property 'id' of undefined
W20160116-14:36:52.053(-7)? (STDERR)     at Neo4jRelationship.<anonymous> (z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\relationship.js:41:65)
W20160116-14:36:52.053(-7)? (STDERR)     at Neo4jRelationship.emit (events.js:95:17)
W20160116-14:36:52.053(-7)? (STDERR)     at new Neo4jRelationship (z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\relationship.js:49:16)
W20160116-14:36:52.054(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseRow (z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\driver.js:408:32)
W20160116-14:36:52.054(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseResponse (z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\driver.js:428:23)
W20160116-14:36:52.054(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__transformData (z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\driver.js:442:43)
W20160116-14:36:52.054(-7)? (STDERR)     at z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\driver.js:219:69
W20160116-14:36:52.055(-7)? (STDERR)     at z:\nwd\nube-medika.meteor\local\isopacks\ostrio-neo4jdriver\npm\node_modules\neo4j-fiber\lib\helpers.js:44:16

The problem is in the relationship. 
{"rest":[{"directions":["->"],"start":"http://localhost:7474/db/data/node/0","nodes":["http://localhost:7474/db/data/node/0","http://localhost:7474/db/data/node/1"],"length":1,"relationships":["http://localhost:7474/db/data/relationship/0"],"end":"http://localhost:7474/db/data/node/1"}]}

has no id or metadata.

If i do a query like 

MATCH (n:User {username: 'admin'})-[r*1..3]->(others) RETURN r

gets the same error.

**Comment by dr-dimitru** [comment]
Could you give a sample data you having in DB, and expected result you're getting from this query while running in Neo4j console

**Comment by dr-dimitru** [comment]
How can relationship have no id?

**Comment by vrfox** [comment]
MATCH p = (n:User {username: 'admin'})-[r*1..3]->(others) RETURN p

Response
Header	Value
Access-control-allow-origin	*
Date	Sat, 16 Jan 2016 22:45:34 GMT
Server	Jetty(9.2.z-SNAPSHOT)
Content-length	767
Content-type	application/json
Data

{
  "results": [
    {
      "columns": [
        "p"
      ],
      "data": [
        {
          "row": [
            [
              {
                "username": "admin",
                "_id": "8GgSoiRY3vLwHSC2i"
              },
              {
                "rel": "patrocinador"
              },
              {
                "username": "marcantuan",
                "_id": "xWikKcZd3R7DEvCjT"
              }
            ]
          ],
          "graph": {
            "nodes": [
              {
                "id": "0",
                "labels": [
                  "User"
                ],
                "properties": {
                  "username": "admin",
                  "_id": "8GgSoiRY3vLwHSC2i"
                }
              },
              {
                "id": "1",
                "labels": [
                  "User"
                ],
                "properties": {
                  "username": "marcantuan",
                  "_id": "xWikKcZd3R7DEvCjT"
                }
              }
            ],
            "relationships": [
              {
                "id": "0",
                "type": "PATROCINADOR",
                "startNode": "0",
                "endNode": "1",
                "properties": {
                  "rel": "patrocinador"
                }
              }
            ]
          }
        }
      ],
      "stats": {
        "contains_updates": false,
        "nodes_created": 0,
        "nodes_deleted": 0,
        "properties_set": 0,
        "relationships_created": 0,
        "relationship_deleted": 0,
        "labels_added": 0,
        "labels_removed": 0,
        "indexes_added": 0,
        "indexes_removed": 0,
        "constraints_added": 0,
        "constraints_removed": 0
      }
    }
  ],
  "errors": []
}

**Comment by vrfox** [comment]
p
[
username	admin
_id	8GgSoiRY3vLwHSC2i
,
rel	patrocinador
,
username	marcantuan
_id	xWikKcZd3R7DEvCjT
]

**Comment by dr-dimitru** [comment]
Neo4j version?

**Comment by vrfox** [comment]
2.3.1

**Comment by dr-dimitru** [comment]
What happens if you run this query via `cypher`?:
```cypher
db. cypher("MATCH p = (n:User {username: 'admin'})-[r*1..3]->(others) RETURN p")
```

**Comment by vrfox** [comment]
db.cypher("MATCH p = (n:User {username: 'admin'})-[r*1..3]->(others) RETURN p")


W20160116-16:03:36.733(-7)? (STDERR)
W20160116-16:03:36.733(-7)? (STDERR) C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\helpers.js:45
W20160116-16:03:36.733(-7)? (STDERR)       }).run();
W20160116-16:03:36.734(-7)? (STDERR)          ^
W20160116-16:03:36.734(-7)? (STDERR) TypeError: Cannot read property 'id' of undefined
W20160116-16:03:36.734(-7)? (STDERR)     at Neo4jRelationship.<anonymous> (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:41:65)
W20160116-16:03:36.734(-7)? (STDERR)     at Neo4jRelationship.emit (events.js:95:17)
W20160116-16:03:36.735(-7)? (STDERR)     at new Neo4jRelationship (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:49:16)
W20160116-16:03:36.735(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseRow (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:408:32)
W20160116-16:03:36.735(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseResponse (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:428:23)
W20160116-16:03:36.736(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__transformData (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:452:23)
W20160116-16:03:36.736(-7)? (STDERR)     at C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:219:69
W20160116-16:03:36.736(-7)? (STDERR)     at C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\helpers.js:44:16
=> Exited with code: 8


seems same error

**Comment by dr-dimitru** [comment]
I see no reason for this issue, as your relationship has an `id`.
Just to try - run query where you're matching any nodes and relationships with `ids` not equal to `0`. I guess when `id` is 0 it is failing.

**Comment by dr-dimitru** [comment]
@vrfox any news on your end?

**Comment by vrfox** [comment]
Hello, i had no chance on Sunday, i get back to this issue today

**Comment by vrfox** [comment]
So I made this query where there is no id:"0".

MATCH p = (n:User {username: 'asdasd'})-[r*1..3]->(others) RETURN p

Response (directly Neo4j)
Data

{
  "results": [
    {
      "columns": [
        "p"
      ],
      "data": [
        {
          "row": [
            [
              {
                "username": "asdasd",
                "patrocinador": "admin",
                "_id": "ZkYQ9Tz67TMthwGkj"
              },
              {},
              {
                "username": "gerardo",
                "patrocinador": "admin",
                "_id": "kLK5dthM85GdA93DY"
              }
            ]
          ],
          "graph": {
            "nodes": [
              {
                "id": "3",
                "labels": [
                  "User"
                ],
                "properties": {
                  "username": "asdasd",
                  "patrocinador": "admin",
                  "_id": "ZkYQ9Tz67TMthwGkj"
                }
              },
              {
                "id": "4",
                "labels": [
                  "User"
                ],
                "properties": {
                  "username": "gerardo",
                  "patrocinador": "admin",
                  "_id": "kLK5dthM85GdA93DY"
                }
              }
            ],
            "relationships": [
              {
                "id": "3",
                "type": "ASCENDENTE",
                "startNode": "3",
                "endNode": "4",
                "properties": {}
              }
            ]
          }
        }
      ],
      "stats": {
        "contains_updates": false,
        "nodes_created": 0,
        "nodes_deleted": 0,
        "properties_set": 0,
        "relationships_created": 0,
        "relationship_deleted": 0,
        "labels_added": 0,
        "labels_removed": 0,
        "indexes_added": 0,
        "indexes_removed": 0,
        "constraints_added": 0,
        "constraints_removed": 0
      }
    }
  ],
  "errors": []
}



METEOR Error:
W20160118-11:03:36.180(-7)? (STDERR)
W20160118-11:03:36.180(-7)? (STDERR) C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\helpers.js:45
W20160118-11:03:36.180(-7)? (STDERR)       }).run();
W20160118-11:03:36.180(-7)? (STDERR)          ^
W20160118-11:03:36.181(-7)? (STDERR) TypeError: Cannot read property 'id' of undefined
W20160118-11:03:36.181(-7)? (STDERR)     at Neo4jRelationship.<anonymous> (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:41:65)
W20160118-11:03:36.182(-7)? (STDERR)     at Neo4jRelationship.emit (events.js:95:17)
W20160118-11:03:36.182(-7)? (STDERR)     at new Neo4jRelationship (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:49:16)
W20160118-11:03:36.182(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseRow (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:408:32)
W20160118-11:03:36.183(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseResponse (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:428:23)
W20160118-11:03:36.183(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__transformData (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:452:23)
W20160118-11:03:36.183(-7)? (STDERR)     at C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:219:69
W20160118-11:03:36.183(-7)? (STDERR)     at C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\helpers.js:44:16
=> Exited with code: 8

**Comment by dr-dimitru** [comment]
I can not reproduce your issue, with same data and query.
To make sure about query and response - could you please run [`batch`](https://github.com/VeliovGroup/neo4j-fiber/wiki/Neo4jDB-Class#batchtasks-settings-callback) request with `plain` flag, like:

```js
db.batch([{
  method: "POST",
  to: db.__service.cypher.endpoint,
  body: {query: "MATCH p = (n:User {username: 'asdasd'})-[r*1..3]->(others) RETURN p"}
}], {plain: true}, function(error, data){
  console.log({error: error, data: data});
});
```

And reply with full console output.
It is more low-level request. Without driver transformations.

**Comment by vrfox** [comment]
I20160118-11:59:05.337(-7)? { error: null,
I20160118-11:59:05.337(-7)?   data: [ { columns: [Object], data: [Object], _batchId: 526210950 } ] }
I20160118-12:00:37.191(-7)? v2.3.1
I20160118-12:00:37.196(-7)? Successfully connected to Neo4j on http://localhost:7474
=> Meteor server restarted
I20160118-12:00:37.680(-7)? {"error":null,"data":[{"columns":["p"],"data":[[{"directions":["->"],"start":"http://localhost:7474/db/data/node/3","nodes":["http://localhost:7474/db/data/node/3","http://localhost:7474/db/data/node/4"],"length":1,"relationships":["http://localhost:7474/db/data/relationship/3"],"end":"http://localhost:7474/db/data/node/4"}]],"_batchId":51922291}]}


The second one is with stringify

**Comment by dr-dimitru** [comment]
Hmmm... looks goo to me. I mean original `query` should not throw an error. What if we now try without `plain` flag?

**Comment by vrfox** [comment]
with plain false it gives error:

W20160118-12:10:12.716(-7)? (STDERR) C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:41
=> Exited with code: 8
W20160118-12:10:12.716(-7)? (STDERR)             _this._id = relationship.id || relationship.metadata.id;
W20160118-12:10:12.717(-7)? (STDERR)                                                                 ^
W20160118-12:10:12.717(-7)? (STDERR) TypeError: Cannot read property 'id' of undefined
W20160118-12:10:12.717(-7)? (STDERR)     at Neo4jRelationship.<anonymous> (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:41:65)
W20160118-12:10:12.718(-7)? (STDERR)     at Neo4jRelationship.emit (events.js:95:17)
W20160118-12:10:12.718(-7)? (STDERR)     at new Neo4jRelationship (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\relationship.js:49:16)
W20160118-12:10:12.718(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseRow (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:408:32)
W20160118-12:10:12.719(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseResponse (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:428:23)
W20160118-12:10:12.719(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__transformData (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:452:23)
W20160118-12:10:12.719(-7)? (STDERR)     at Neo4jDB.<anonymous> (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:865:67)
W20160118-12:10:12.719(-7)? (STDERR)     at Neo4jDB.g (events.js:180:16)
W20160118-12:10:12.720(-7)? (STDERR)     at Neo4jDB.emit (events.js:106:17)
W20160118-12:10:12.720(-7)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__proceedResult (C:\Users\vr_fo\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2-fiber\npm\node_modules\neo4j-fiber\lib\driver.js:171:23)

**Comment by dr-dimitru** [comment]
I'll put my hand on it day after tomorrow. Need more time to investigate.
Any other queries expecting same issue?

**Comment by vrfox** [comment]
the same goes returning the relation chips not the path:

query: "MATCH p = (n:User {username: 'asdasd'})-[r*1..3]->(others) RETURN **r**"
query: "MATCH p = (n:User {username: 'asdasd'})-[r*1..3]->(others) RETURN **p**"

**Comment by vrfox** [comment]
Any news on this issue?
