### ISSUE TITLE
Error when creating nodes/relationships with a lot of data

### ISSUE THREAD

**Issue by mexin** [VeliovGroup/ostrio-neo4jdriver#44]
Hello I'm getting this error

```
Error sending request to Neo4j (GrapheneDB) server: Error: socket hang up
Empty response from Neo4j, but expecting data
Error: TypeError: Cannot read property 'data' of undefined
```
it's really random and happens when importing 100k records to Neo4j, 

Is there an example on how to do huge insertions?

Meteor 1.5

Thank you!

**Comment by dr-dimitru** [comment]
Hello @mexin ,

Sure, I'm suggesting to use [transactions API](https://github.com/VeliovGroup/neo4j-fiber/wiki/Neo4jTransaction-Class). And split 100K by 10K per each `.commit()`.

Let me know if it works for you.

**Comment by dr-dimitru** [comment]
Hello @mexin ,

Any news on this one? Have you implemented it with transactional API?
//cc @mksh-su

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
