### ISSUE TITLE
Meteor 1.4.4.3 import issue

### ISSUE THREAD

**Issue by risingsunxy** [VeliovGroup/ostrio-neo4jdriver#45]
import { Neo4jDB } from 'meteor/ostrio:neo4jdriver';
console.log(Neo4jDB);
return undefined

const Neo4jDB  = require('meteor/ostrio:neo4jdriver').Neo4jDB;
console.log(Neo4jDB);
also return undefined

is this a known issue,please?

**Comment by dr-dimitru** [comment]
Hello @risingsunxy ,

 1. Is this *Client* or *Server*? (Note: __This is server-side only package__)
 2. I recommend to use NPM version of the package as Meteor is moving towards NPM ecosystem - https://www.npmjs.com/package/neo4j-fiber

**Comment by risingsunxy** [comment]
Hi Dr-dimitru,

thanks a lot for your reply!
it works now :)

**Comment by dr-dimitru** [comment]
Great :) I'm glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/ostrio-neo4jdriver)
 - Star on [NPM](https://www.npmjs.com/package/neo4j-fiber)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/neo4jdriver)
